# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 09:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdv_id', models.IntegerField()),
                ('population', models.FloatField()),
                ('agriculteu', models.FloatField()),
                ('artisans', models.FloatField()),
                ('cadres', models.FloatField()),
                ('prof_inter', models.FloatField()),
                ('employes', models.FloatField()),
                ('ouvriers', models.FloatField()),
                ('chomeurs', models.FloatField()),
                ('retraites', models.FloatField()),
                ('proprietai', models.FloatField()),
                ('immigrant', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
